############################
# rsyslog.conf (Ubuntu/Debian) - Drop k8s logs
############################

module(load="imuxsock")
module(load="imjournal")
module(load="imklog")
module(load="omkafka")

global(workDirectory="/var/lib/rsyslog")

main_queue(
  queue.type="LinkedList"
  queue.size="50000"
)

template(name="KafkaJson" type="list") {
  constant(value="{")
    constant(value="\"timestamp\":\"") property(name="timereported" dateFormat="rfc3339")
    constant(value="\",\"host\":\"") property(name="hostname")
    constant(value="\",\"program\":\"") property(name="programname")
    constant(value="\",\"msg\":\"") property(name="msg" format="json")
  constant(value="\"}")
}

*.info;mail.none;authpriv.none;cron.none    /var/log/syslog
authpriv.*                                  /var/log/auth.log
mail.*                                      -/var/log/mail.log
cron.*                                      /var/log/syslog

if (
    $programname == 'kubelet' or
    $programname == 'containerd' or
    $programname == 'kube-proxy' or
    $programname startswith 'calico'
   ) then {
    stop
}

action(
  type="omkafka"
  broker=["kafka1:9092","kafka2:9092"]
  topic="system-log"
  template="KafkaJson"
)
