apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: build-robot       # ServiceAccount 등록
  automountServiceAccountToken: false   # 등록한 ServiceAccount의 Token이 mount되지 않도록 설정 
  ...


########## 환경 변수 사용 ######################
apiVersion: v1
kind: Pod
metadata:
  name: print-greeting
  namespace: dev
  labels:
    app: test
  annotations:
    buildversion: 1.34
spec:
  nodeName: null
  containers:
  - name: env-print-demo
    image: bash
    ports:
    - containerPort: 80807
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most Honorable"
    - name: NAME
      value: "Kubernetes"
    command: ["echo"]
    args: ["$(GREETING) $(HONORIFIC) $(NAME)"]
    # command:
    
  imagePullSecrets:
  - name: myregistrykey

