description: |-
  *Replace this default text with instructions or other information about your document.*  

  ---
  # What is Markdown?
  Markdown is a lightweight markup language that converts your content with plain text formatting to structurally valid rich text.
  ## You can add headings
  You can add *italics* or make the font **bold**.  
  1. Create numbered lists 
  * Add bullet points 
  >Indent `code samples` 

  You can create a [link to another webpage](https://aws.amazon.com/).
schemaVersion: '0.3'
parameters:
  allOrOne:
    type: String
    default: 'one'
  drAutomationName:
    type: String
    default: 'test'
mainSteps:
  - name: 'selectDrAutomation'
    action: 'aws:branch'
    inputs:
      Choices:
        - NextStep: 'countAllDRAutomation'
          Variable: "{{ allOrOne }}"
          StringEquals: 'all'
        - NextStep: 'executeOneDrAutomation'
          Variable: "{{ allOrOne }}"
          StringEquals: 'one'
      Default:
        'sleep1s'
    
    - name: 'checkAllDRAutomationCount'
      action: 'aws:executeAwsApi'
      inputs:
        Service: 
        Api:
      outputs:
        - Name: 'allDRAutomationCount'
          Selector: '$.Images[0].ImageId'
          Type: String
      nextStep: 'executeAllDrAutomation'

    - name: 'executeAllDrAutomation'
      action: 'aws:executeAutomation'
      inputs:
        DocumentName: "{{ drAutomationName }}"
        MaxConcurrency: '100%'
        MaxErrors: '100%'

        RuntimeParameters:


    - name: 'executeOneDrAutomation'
      action: 'aws:executeAutomation'
      inputs:
        DocumentName: "{{ drAutomationName }}"
        RuntimeParameters:

    - name: 'sleep1s'
      action: 'aws:sleep'
      inputs:
        Duration: 
      






