description: |-
  *Replace this default text with instructions or other information about your document.*  

  ---
  # What is Markdown?
  Markdown is a lightweight markup language that converts your content with plain text formatting to structurally valid rich text.
  ## You can add headings
  You can add *italics* or make the font **bold**.  
  1. Create numbered lists 
  * Add bullet points 
  >Indent `code samples` 

  You can create a [link to another webpage](https://aws.amazon.com/).
schemaVersion: '0.3'
parameters:
  allOrOne:
    type: String
<<<<<<< HEAD
    default: one
  drAutomationName:
    type: String
    default: test
  drResourceGroup:
    type: String
    default: test
=======
    description: "all : execute all dr automaion/ one : execute specific dr automation"
    default: 'one'
    allowedPattern: ""
    maxItems: 1
  drAutomationName:
    type: String
    default: 'test'
    maxItems: 1
>>>>>>> ac40b8c63855c6d80ad29679c7b50b498c43ddf6
mainSteps:
  - name: selectDrAutomation
    action: 'aws:branch'
    inputs:
      Choices:
<<<<<<< HEAD
        - NextStep: executeAllDrAutomation
          Variable: '{{ allOrOne }}'
          StringEquals: all
        - NextStep: executeOneDrAutomation
          Variable: '{{ allOrOne }}'
          StringEquals: one
      Default: sleep1s
  - name: executeAllDrAutomation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: '{{ drAutomationName }}'
      MaxConcurrency: 100%
      MaxErrors: 100%
      TargetParameterName: 'drAutomationName'
      Targets:
        - Key: 'resource-groups:Name'
          Value: '{{ drResourceGroup }}'
  - name: executeOneDrAutomation
    action: 'aws:executeAutomation'
    inputs:
      DocumentName: '{{ drAutomationName }}'
  - name: sleep1s
    action: 'aws:sleep'
    inputs:
      Duration: PT10S
=======
        - NextStep: 'executeAllDRAutomation'
          Variable: "{{ allOrOne }}"
          StringEquals: 'all'
        - NextStep: 'executeOneDrAutomation'
          Variable: "{{ allOrOne }}"
          StringEquals: 'one'
      Default:
        'sleep10s'
    - name: 'executeAllDrAutomation'
      action: 'aws:executeAutomation'
      inputs:
        DocumentName: "{{ drAutomationName }}"
        MaxConcurrency: '100%'
        MaxErrors: '100%'
      isEnd: true
    - name: 'executeOneDrAutomation'
      action: 'aws:executeAutomation'
      inputs:
        DocumentName: "{{ drAutomationName }}"
        RuntimeParameters:
      isEnd: true
    - name: 'sleep10s'
      action: 'aws:sleep'
      inputs:
        Duration: PT10S
      isEnd: true
>>>>>>> ac40b8c63855c6d80ad29679c7b50b498c43ddf6






