all:
    hosts:
        172.16.30.91
    children:
        webservers:
            hosts:
                dev:
                    ansible_host: 172.16.30.92
                    ansible_port: 40022
                prd:
                    ansible_host: 172.16.30.93
                    ansible_port: 40022
                vars:
                    ntp_server: ntp.atlanta.example.com
                    proxy: proxy.atlanta.example.com
        wasservers:
            hosts:
                17[1:10].16.30.85
                172.16.30.95



